# Mappings
[mappings]
  leader = " "
	[mappings.vim]
  # Refer to https://github.com/mrjones2014/legendary.nvim#configuration-and-setup for more info on how to initialise mappings
  [mappings.telescope]

# Options
[opts]
	# Vim specific options
	[opts.vim]
	  undodir = "/home/naruto/.cache/nvim/undo"

	# NVSC specific options
	[opts.nvsc]
	pre_func = '''
		vim.g.sqlite_clib_path = require("nvsc.utils").fs.read_file(vim.fn.stdpath("config") .. "/sqlite_path")
	'''

[plugins]
	# Disabled Plugins
	disabled_plugins = [
		"themercorp/themer.lua"
	]
	
	# Extra plugins to load
	# Just like how you initialise plugins in packer
	[plugins.extra_plugins."~/projects/nvim_plugins/themer"]	
	  event = "BufEnter"
	  config = '''
	      require("themer").setup({
	          colorscheme = "rose_pine",
	          styles = {
	            	["function"] = { style = 'italic' },
	             	functionbuiltin = { style = 'italic' },
	             	variable = { style = 'italic' },
	              	variableBuiltIn = { style = 'italic' },
	            	parameter  = { style = 'italic' },
	          },
	      })
	  '''
[lsp]
  servers = [  
    "sumneko_lua",
    "pyright",
    "vuels",
    "tsserver",
    "svelte",
    "html",
    "cssls",
    "jsonls",
    "gopls",
    "pyright",
    "rust_analyzer",
    "rnix"
  ]
