# Mappings
[mappings]
	# Refer to https://github.com/mrjones2014/legendary.nvim#configuration-and-setup for more info on how to initialise mappings

# Options
[opts]
	# Vim specific options
	[opts.vim]
	undodir = "/home/naruto/.cache/nvim/undo"

	# NVSC specific options
	[opts.nvsc]

[plugins]
	# Disabled Plugins
	disabled_plugins = [
		"themercorp/themer.lua"
	]
	
	# Extra plugins to load
	# Just like how you initialise plugins in packer
	[plugins.extra_plugins."~/projects/nvim_plugins/themer"]	
	event = "BufEnter"
	config = '''
	    require("themer").setup({
	        colorscheme = "rose_pine",
	        styles = {
	          	["function"] = { style = 'italic' },
	           	functionbuiltin = { style = 'italic' },
	           	variable = { style = 'italic' },
	            	variableBuiltIn = { style = 'italic' },
	          	parameter  = { style = 'italic' },
	        },
	    })
	'''
